# Generated by Django 5.0.6 on 2024-06-27 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 0, 55, 16, 348658, tzinfo=datetime.timezone.utc)),
        ),
    ]
