# Generated by Django 5.0.6 on 2024-06-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
