# Generated by Django 5.0.6 on 2024-06-27 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_arquivo_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='arquivo_txt',
        ),
        migrations.CreateModel(
            name='ResponseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='responses/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_files', to='projects.project')),
            ],
        ),
    ]
